### ISSUE TITLE
Output options are blocked.

### ISSUE THREAD

**Issue by tconnard** [attila/metalsmith-rollup#2]
At the moment using output options prevents the plugin from running.
```
Error: Unexpected key 'output' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
    at validateKeys (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-rollup\node_modules\rollup\dist\rollup.js:1212:11)
    at Object.rollup (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-rollup\node_modules\rollup\dist\rollup.js:8048:14)
    at Ware.pluginOutput (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-rollup\lib\index.js:23:12)
    at Ware.<anonymous> (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\wrap-fn\index.js:45:19)
    at next (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\ware\lib\index.js:85:20)
    at E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\wrap-fn\index.js:121:18
    at E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-sass\node_modules\async\internal\once.js:12:16
    at iteratorCallback (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-sass\node_modules\async\eachOf.js:60:13)
    at E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-sass\node_modules\async\internal\onlyOnce.js:12:16
    at Object.callback (E:\msys64\home\Thomas\cos10011-assignment-2\node_modules\metalsmith-sass\lib\index.js:100:13)```

**Comment by attila** [comment]
Thanks for reporting this @tconnard 👍
